### ISSUE TITLE
Account recovery

### ISSUE THREAD

**Issue by rdevries-thoughtworks** [pixelated/pixelated-user-agent#808]
_spawned from #791, relates to #802, estimation: 17 points_

Implement the account recovery workflow described in #754. That is: entering the previously created (#802) recovery code and the new password.

For **Soledad**, we should add (something like) `Soledad.recover_account(recovery_code)` to LEAP's Soledad client.

For **Bonafide**, we should add a flow similar to login, with a handshake `/recovery(.json)` and a `/recovery/:login(.json)` endpoint, to the Bonafide server (RoR web app). The first endpoint is like `/session(.json)`, but `/session(.json)` can't be used as a handshake for account recovery. The second endpoint doesn't only start a session, but also changes the password; it leaves the recovery_code unchanged. Of course there should be a Bonafide client implementation for this API call too.

To prevent users being locked out of their accounts, **Pixelated** should only start removing the recovery code when the password change has completed successfully in both Bonafide and Soledad. This way, during the whole flow, either the recovery_code will still work, or the new password will already work.

**Acceptance criteria**

- for every HTTP request in this flow, for failure during both request/response, either the (old) recovery code still works, or the new password already works (for both Soledad and Bonafide)
- after account recovery, both the old password and the old recovery don't work anymore.
- the session handshake can't be used for account recovery

**Tasks**
- [ ] Add `Soledad.recover_account(recovery_code)` to LEAP's Soledad client _[1 point]_
- [ ] Add recovery endpoints to the Bonafide server _[5 points]_
- [ ] Add `Session.recover_account` to LEAP's Bonafide client _[3 points]_
- [ ] Add Pixelated front-end and coordinate the account recovery of Bonafide and Soledad _[8 points]_

**Comment by rdevries-thoughtworks** [comment]
Open question: @azul how to do account recovery with Bonafide? Currently there doesn't seem to be a way to change your password if you've forgotten it.

**Comment by rdevries-thoughtworks** [comment]
Closing this issue because it's split into #877, #878, #879 and #880.
